### ISSUE TITLE
"Unknown error" during display of Root CA Certificate

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#363] opened 2016-04-06 07:43 UTC
Assumption: multi-level PKI (at least Root + Issuing CA).
On the UI click "Information" -> "CA Certificates".
Pick one issuing CA.
Click on Issuer link (Root CA cert subject link)
On the "Certificate Chain" dialog click on the subject of the Root CA again.
On the interface behind the popup dialog a red box with "Unknown error" is displayed. After closing the popup, the error remains.

**Comment by stefanomarty** [comment] 2016-04-06 08:29
I confirm I have the same error here (I'm quite sure it wasn't there before upgrading to 1.7.0

I have the "unknown error" message also in the "My Tasks" menu:
- Enter as Operator
- Just click "Home" --> "My Tasks"
- Got "Unknown error in the red box
- Tasks are shown nevertheless

I'm using a testing installation, but I never touched the database values outside the OpenXPKI application.

**Comment by oliwel** [comment] 2016-04-06 10:57
can you check the webui.log for anything that helps what gets triggered. In both cases it looks like a superfluous call is made that can not be answered.
I can confirm/reproduce the bug from @mbartosch  but I cant the one from @stefanomarty

**Comment by oliwel** [comment] 2016-04-06 11:22
@stefanomarty: I fixed the bug from the inital ticket. If you can reproduce your problem please open a new ticket, I will close this one.

**Closed by oliwel** 2016-04-06 11:22 UTC
Labels: bug, frontend, low priority
